[tox]
no_package = true
env_list = py314-64bit, py39-64bit
skip_missing_interpreters = false

[testenv]
description = check if drivers can be imported
basepython =
    py39-64bit: python3.9-64
    py314-64bit: python3.14-64
allowlist_externals = pwsh
deps =
    py39-64bit: -r .github/requirements_39.txt
    py314-64bit: -r requirements.txt
passenv = 
    LOCALAPPDATA #required for win32 certifi
commands =
    pwsh -NoProfile -Command .\.github\Test-Importability.ps1
