# This is an autogenerated file. Changes may be overwritten.

LOT_Exception_Map = {}

def lookup_exception(number):
    if number in LOT_Exception_Map.keys():
        return LOT_Exception_Map[number]
    else:
        raise ValueError("No LOT exception matches this return value: "+str(number))

class LOT_Error(EnvironmentError):
    id = -1
LOT_Exception_Map[-1]=LOT_Error

class LOT_File_Not_Found(EnvironmentError):
    id = 1
LOT_Exception_Map[1]=LOT_File_Not_Found

class LOT_Invalid_System_Model(ValueError):
    id = 2
LOT_Exception_Map[2]=LOT_Invalid_System_Model

class LOT_Invalid_Group(ValueError):
    id = 3
LOT_Exception_Map[3]=LOT_Invalid_Group

class LOT_Invalid_Slave(ValueError):
    id = 4
LOT_Exception_Map[4]=LOT_Invalid_Slave

class LOT_No_Groups_Exist(EnvironmentError):
    id = 5
LOT_Exception_Map[5]=LOT_No_Groups_Exist

class LOT_Duplicate_ID(ValueError):
    id = 6
LOT_Exception_Map[6]=LOT_Duplicate_ID

class LOT_System_Not_Initialised(RuntimeError):
    id = 7
LOT_Exception_Map[7]=LOT_System_Not_Initialised

class LOT_Invalid_ID(ValueError):
    id = 8
LOT_Exception_Map[8]=LOT_Invalid_ID

class LOT_Invalid_Token(ValueError):
    id = 9
LOT_Exception_Map[9]=LOT_Invalid_Token

class LOT_Invalid_Attribute(AttributeError):
    id = 10
LOT_Exception_Map[10]=LOT_Invalid_Attribute

class LOT_Invalid_Index(IndexError):
    id = 11
LOT_Exception_Map[11]=LOT_Invalid_Index

class LOT_Invalid_Setup(EnvironmentError):
    id = 12
LOT_Exception_Map[12]=LOT_Invalid_Setup

class LOT_Invalid_Value(ValueError):
    id = 13
LOT_Exception_Map[13]=LOT_Invalid_Value

class LOT_Error_USB_Disconnected(IOError):
    id = 14
LOT_Exception_Map[14]=LOT_Error_USB_Disconnected

class LOT_USB_Comms_Not_Initialised(IOError):
    id = 15
LOT_Exception_Map[15]=LOT_USB_Comms_Not_Initialised

class LOT_Invalid_SMDType(ValueError):
    id = 16
LOT_Exception_Map[16]=LOT_Invalid_SMDType

class LOT_Invalid_Comms(IOError):
    id = 17
LOT_Exception_Map[17]=LOT_Invalid_Comms

class LOT_Error_IMAC_timeout(IOError):
    id = 18
LOT_Exception_Map[18]=LOT_Error_IMAC_timeout

class LOT_USB_Comms_Error(IOError):
    id = 19
LOT_Exception_Map[19]=LOT_USB_Comms_Error

class LOT_Invalid_Turret_Wavelength(ValueError):
    id = 20
LOT_Exception_Map[20]=LOT_Invalid_Turret_Wavelength

class LOT_Invalid_Filter_Pos(ValueError):
    id = 21
LOT_Exception_Map[21]=LOT_Invalid_Filter_Pos

class LOT_Invalid_Slit_Width(ValueError):
    id = 22
LOT_Exception_Map[22]=LOT_Invalid_Slit_Width

class LOT_Invalid_Hardware_Type(ValueError):
    id = 23
LOT_Exception_Map[23]=LOT_Invalid_Hardware_Type

class LOT_Invalid_Slit_Type(ValueError):
    id = 24
LOT_Exception_Map[24]=LOT_Invalid_Slit_Type

class LOT_Invalid_Grating(ValueError):
    id = 25
LOT_Exception_Map[25]=LOT_Invalid_Grating

class LOT_Invalid_Turret(ValueError):
    id = 26
LOT_Exception_Map[26]=LOT_Invalid_Turret

class LOT_Invalid_SAM_State(ValueError):
    id = 27
LOT_Exception_Map[27]=LOT_Invalid_SAM_State

class LOT_Error_Undefined(RuntimeError):
    id = 100
LOT_Exception_Map[100]=LOT_Error_Undefined
