# This is an autogenerated file. Changes may be overwritten.

LOT_Token_Dict = {}

def lookup_token(val):
    if val in LOT_Token_Dict.keys():
        return LOT_Token_Dict[val]
    else:
        raise ValueError("No LOT token matches this id or value: "+str(val))

MonochromatorScanDirection=10
LOT_Token_Dict[10]='MonochromatorScanDirection'
LOT_Token_Dict['MonochromatorScanDirection']=10

MonochromatorCurrentWL=11
LOT_Token_Dict[11]='MonochromatorCurrentWL'
LOT_Token_Dict['MonochromatorCurrentWL']=11

MonochromatorCurrentGrating=12
LOT_Token_Dict[12]='MonochromatorCurrentGrating'
LOT_Token_Dict['MonochromatorCurrentGrating']=12

MonochromatorInitialise=13
LOT_Token_Dict[13]='MonochromatorInitialise'
LOT_Token_Dict['MonochromatorInitialise']=13

MonochromatorModeSwitchNum=14
LOT_Token_Dict[14]='MonochromatorModeSwitchNum'
LOT_Token_Dict['MonochromatorModeSwitchNum']=14

MonochromatorModeSwitchState=15
LOT_Token_Dict[15]='MonochromatorModeSwitchState'
LOT_Token_Dict['MonochromatorModeSwitchState']=15

MonochromatorCanModeSwitch=16
LOT_Token_Dict[16]='MonochromatorCanModeSwitch'
LOT_Token_Dict['MonochromatorCanModeSwitch']=16

MonochromatorAutoSelectWavelength=17
LOT_Token_Dict[17]='MonochromatorAutoSelectWavelength'
LOT_Token_Dict['MonochromatorAutoSelectWavelength']=17

MonochromatorZordSwitchSAM=18
LOT_Token_Dict[18]='MonochromatorZordSwitchSAM'
LOT_Token_Dict['MonochromatorZordSwitchSAM']=18

MonochromatorNumTurrets=19
LOT_Token_Dict[19]='MonochromatorNumTurrets'
LOT_Token_Dict['MonochromatorNumTurrets']=19

MonochromatorCosAlpha=21
LOT_Token_Dict[21]='MonochromatorCosAlpha'
LOT_Token_Dict['MonochromatorCosAlpha']=21

TurretNumGratings=20
LOT_Token_Dict[20]='TurretNumGratings'
LOT_Token_Dict['TurretNumGratings']=20

GratingDensity=30
LOT_Token_Dict[30]='GratingDensity'
LOT_Token_Dict['GratingDensity']=30

GratingZord=31
LOT_Token_Dict[31]='GratingZord'
LOT_Token_Dict['GratingZord']=31

GratingAlpha=32
LOT_Token_Dict[32]='GratingAlpha'
LOT_Token_Dict['GratingAlpha']=32

GratingSwitchWL=33
LOT_Token_Dict[33]='GratingSwitchWL'
LOT_Token_Dict['GratingSwitchWL']=33

GratingBlaze=34
LOT_Token_Dict[34]='GratingBlaze'
LOT_Token_Dict['GratingBlaze']=34

FWheelFilter=100
LOT_Token_Dict[100]='FWheelFilter'
LOT_Token_Dict['FWheelFilter']=100

FWheelPositions=101
LOT_Token_Dict[101]='FWheelPositions'
LOT_Token_Dict['FWheelPositions']=101

FWheelCurrentPosition=102
LOT_Token_Dict[102]='FWheelCurrentPosition'
LOT_Token_Dict['FWheelCurrentPosition']=102

SAMInitialState=300
LOT_Token_Dict[300]='SAMInitialState'
LOT_Token_Dict['SAMInitialState']=300

SAMSwitchWL=301
LOT_Token_Dict[301]='SAMSwitchWL'
LOT_Token_Dict['SAMSwitchWL']=301

SAMState=302
LOT_Token_Dict[302]='SAMState'
LOT_Token_Dict['SAMState']=302

SAMCurrentState=303
LOT_Token_Dict[303]='SAMCurrentState'
LOT_Token_Dict['SAMCurrentState']=303

SAMDeflectName=304
LOT_Token_Dict[304]='SAMDeflectName'
LOT_Token_Dict['SAMDeflectName']=304

SAMNoDeflectName=305
LOT_Token_Dict[305]='SAMNoDeflectName'
LOT_Token_Dict['SAMNoDeflectName']=305

MVSSSwitchWL=401
LOT_Token_Dict[401]='MVSSSwitchWL'
LOT_Token_Dict['MVSSSwitchWL']=401

MVSSWidth=402
LOT_Token_Dict[402]='MVSSWidth'
LOT_Token_Dict['MVSSWidth']=402

MVSSCurrentWidth=403
LOT_Token_Dict[403]='MVSSCurrentWidth'
LOT_Token_Dict['MVSSCurrentWidth']=403

MVSSConstantBandwidth=404
LOT_Token_Dict[404]='MVSSConstantBandwidth'
LOT_Token_Dict['MVSSConstantBandwidth']=404

MVSSConstantwidth=405
LOT_Token_Dict[405]='MVSSConstantwidth'
LOT_Token_Dict['MVSSConstantwidth']=405

MVSSSlitMode=406
LOT_Token_Dict[406]='MVSSSlitMode'
LOT_Token_Dict['MVSSSlitMode']=406

MVSSPosition=407
LOT_Token_Dict[407]='MVSSPosition'
LOT_Token_Dict['MVSSPosition']=407

MVSSCurrentBandwidth=408
LOT_Token_Dict[408]='MVSSCurrentBandwidth'
LOT_Token_Dict['MVSSCurrentBandwidth']=408

SimulationMode=500
LOT_Token_Dict[500]='SimulationMode'
LOT_Token_Dict['SimulationMode']=500

lotSettleDelay=1000
LOT_Token_Dict[1000]='lotSettleDelay'
LOT_Token_Dict['lotSettleDelay']=1000

lotMoveWithWavelength=1001
LOT_Token_Dict[1001]='lotMoveWithWavelength'
LOT_Token_Dict['lotMoveWithWavelength']=1001

lotDescriptor=1002
LOT_Token_Dict[1002]='lotDescriptor'
LOT_Token_Dict['lotDescriptor']=1002

lotParkOffset=1003
LOT_Token_Dict[1003]='lotParkOffset'
LOT_Token_Dict['lotParkOffset']=1003

lotProductName=1004
LOT_Token_Dict[1004]='lotProductName'
LOT_Token_Dict['lotProductName']=1004

lotInterface=10000
LOT_Token_Dict[10000]='lotInterface'
LOT_Token_Dict['lotInterface']=10000

lotSAM=10001
LOT_Token_Dict[10001]='lotSAM'
LOT_Token_Dict['lotSAM']=10001

lotSlit=10002
LOT_Token_Dict[10002]='lotSlit'
LOT_Token_Dict['lotSlit']=10002

lotFilterWheel=10003
LOT_Token_Dict[10003]='lotFilterWheel'
LOT_Token_Dict['lotFilterWheel']=10003

lotMono=10004
LOT_Token_Dict[10004]='lotMono'
LOT_Token_Dict['lotMono']=10004

lotUnknown=10011
LOT_Token_Dict[10011]='lotUnknown'
LOT_Token_Dict['lotUnknown']=10011
